apiVersion: v1
kind: Secret
metadata:
  name: movie-db-secret
type: Opaque
data:
  POSTGRES_USER: bW92aWVfZGJfdXNlcm5hbWU=
  POSTGRES_PASSWORD: bW92aWVfZGJfcGFzc3dvcmQ=
  POSTGRES_DB: bW92aWVfZGJfZGV2
