apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movie-db-pvc
  labels:
    app: {{ .Release.Name }}
spec:
  accessModes: {{ .Values.persistence.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
