replicaCount: 1

image:
  repository: postgres
  tag: "12.1-alpine"

service:
  type: ClusterIP
  port: 5432

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 1Gi

secretName: cast-db-secret
