replicaCount: 1

image:
  repository: asmalhb/cast-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

env:
  databaseUri: "postgresql://cast_db_username:cast_db_password@cast-db/cast_db_dev"
